services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.1.1
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
    environment:
      HOMEPAGE_ALLOWED_HOSTS: localhost:3000
      LOG_TARGETS: stdout